# Main Hydra configuration file.
defaults:
  - network: TBNN
  - dataset: target_net
  - optimizer: ExpectationSGD
  - loss: l1
  # Pretty logging with hydra_colorlog
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  # Launcher
  - override hydra/launcher: ray
  - _self_

train:
  epochs: 10
  log_rate: 1
  log_lr: 0.0000001
  batch_size: 2048
  gpu: 0
  checkpoint_rate: 1
  save_dir: ~/tmp/test/
  description: 'none'

hydra:
  # Logging configuration: https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
  verbose: False
  # Logs to stdout and to a file.
  job_logging:
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
      file:
        filename:
          ${hydra.runtime.output_dir}/${hydra.job.name}_${oc.select:hydra.job.num, 0}.log
  # Set the output directory to /tmp to dump logs.
  run:
    dir: /tmp/hydra/logs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir:  /tmp/hydra/logs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
