# The Conda environment specification for bnn
name: bnn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
# Core pip packages
    - -r requirements.txt
# Linting and development
    - -r requirements_dev.txt