input_dim: 7
hidden_dims: [10]
output_dim: 7

data_loader:
  _target_: bnn.data.TargetNetworkDataLoader
  datapoints: ${train.batch_size}
  batch_size: ${train.batch_size}
  include_last_if_uneven: True
  W_mean: 0
  W_zero_prob: 0.8
  target_network:
    _target_: bnn.network.TernBinNetwork
    dims: ${sandwich_list:${dataset.input_dim},${dataset.hidden_dims},${dataset.output_dim}}
    forward_func:
      _target_: bnn.functions.forward.SignBinarise
    backward_func: null

train_data_loader: ${data.data_loader}
test_data_loader: ${data.data_loader}
